security:
    enable_authenticator_manager: true
    encoders:
        App\Entity\User:
            algorithm: auto
        App\Entity\UserApi:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
        app_user_api:
            entity:
                class: App\Entity\UserApi
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/v1/.+
            stateless: true
            anonymous: false
            provider: app_user_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
        main:
            provider: app_user_provider
            switch_user: { role: ROLE_ADMIN }
            context: website
            pattern: ^/admin
            form_login:
                provider: app_user_provider
                always_use_default_target_path: true
                check_path: /admin/login
                login_path: /admin/login
                use_forward: true
                username_parameter: email
                password_parameter: password
                default_target_path: /admin
            logout:
                path: /api/logout
                target: /
            entry_point: form_login

    access_control:
        - { path: ^/admin/login, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: [ ROLE_ADMIN ] }
        - { path: ^/api/security/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/v1/.+, roles: ROLE_CLIENT }

    role_hierarchy:
        ROLE_CLIENT: [ROLE_USER]
        ROLE_ADMIN: [ROLE_CLIENT]