# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: symfony
          MYSQL_DATABASE: symfony
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Validate composer.json & composer.lock
        run: composer validate

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: PHP Composer
        uses: php-actions/composer@v5
      
      - name: PHPStan (php-actions)
      # You may pin to the exact commit or the version.
      # uses: php-actions/phpstan@e1ce60d6e66d508e78ddeefac1ec81570b8ef27d
        uses: php-actions/phpstan@v2
        with:
          # What version of PHP to use
          php_version: 7.4
          # Path(s) with source code to run analysis on
          path: src
          # Level of rule options - the higher, the stricter
          level: 6
          # Memory limit for analysis
          memory_limit: 0

      - name: PHPCS
        # You may pin to the exact commit or the version.
        # uses: php-actions/phpstan@e1ce60d6e66d508e78ddeefac1ec81570b8ef27d
        run:  ./vendor/bin/phpcs -v

      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
